services:
  webtjeneste:
    image: nginx
    ports:
    - "8080:80"
    volumes:
      - './html:/var/www/html'
      - './html:/var/www/html/css'
      - './nginx-conf:/etc/nginx/conf.d'
    restart: always